/* 블루메시지 서비스 */
CREATE TABLE `BLUE_MESSAGE` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',

  `NAME`				VARCHAR(20)				DEFAULT ''			NOT NULL COMMENT '이름',
  `TEL`					VARCHAR(11)				DEFAULT ''			NOT NULL COMMENT '연락처',
  `BIRTHDAY`			DATE										NOT NULL COMMENT '생일',
  `GENDER`				ENUM('남','여','')		DEFAULT ''			NOT NULL COMMENT '성별',

  `RECEIVE_NEW`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '신제품 런칭 정보',
  `RECEIVE_STYLING`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '스타일링 제안',
  `RECEIVE_REORDER`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '재입고 안내',

  `REMARK`				VARCHAR(2000)			DEFAULT ''			NOT NULL COMMENT '비고',
  `IP`					VARCHAR(15)				DEFAULT '0.0.0.0'	NOT NULL COMMENT 'IP',

  `STATUS`				ENUM('등록','거부','삭제')	DEFAULT '등록'		NOT NULL COMMENT '상태',

  `FINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '최초작성시간',
  `LINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '최종수정시간',

  INDEX `INDEX_BLUE_MESSAGE` (`STATUS`,`RECEIVE_NEW`,`RECEIVE_STYLING`,`RECEIVE_REORDER`,`NAME`,`TEL`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='블루메시지 서비스';
