FROM php:8.2-apache

LABEL description="This is an example Dockerfile for Apache with PHP 8.2."

# Install tools and clean up
RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
        apt-utils \
        curl \
        git \
        openssl \
        nano \
        cron \
        graphicsmagick \
        imagemagick \
        ghostscript \
        ca-certificates \
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install MySQL client
RUN apt-get update && \
    apt-get install -y --no-install-recommends default-mysql-client \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable Apache modules
RUN a2enmod rewrite ssl

RUN docker-php-ext-install mysqli

RUN echo "short_open_tag = On" >> /usr/local/etc/php/php.ini

# Fix timezone issue
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./000-default.conf /etc/apache2/sites-available/

EXPOSE 80 443 7080

CMD ["apachectl", "-D", "FOREGROUND"]

