/* COVID19 */
CREATE TABLE `OFFLINE_ENTERANCE` (
  `IDX`			INT(10) UNSIGNED					NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `STORE`		VARCHAR(30)			DEFAULT ''		NOT NULL,
  `NAME`		VARCHAR(20)			DEFAULT ''		NOT NULL,
  `TEL`			VARCHAR(14)			DEFAULT ''		NOT NULL,
  `TEL_CP`		VARCHAR(20)			DEFAULT ''		NOT NULL,
  `TEL_CODE`	VARCHAR(20)			DEFAULT ''		NOT NULL,
  `TEL_VERTIFY_DATE`	DATETIME							NULL,
  `EMAIL`		VARCHAR(200)		DEFAULT ''		NOT NULL,
  `INSTAGRAM_ID`		VARCHAR(40)		DEFAULT ''		NOT NULL,
  `IP`			VARCHAR(15)		DEFAULT ''		NOT NULL,

  `INPUT_DATE`	DATETIME			DEFAULT NOW()			NOT NULL,
  
  INDEX `INDEX_OFFLINE_ENTERANCE` (`NAME`,`STORE`,`TEL`,`EMAIL`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


/* 컨텐츠 */
CREATE TABLE `PAGE` (
  `IDX`			INT(10) UNSIGNED				NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `SEQ`			INT(10) UNSIGNED	DEFAULT 1		NOT NULL,

  `CODE`		VARCHAR(20)		DEFAULT ''		NOT NULL,
  `YEAR`		VARCHAR(4)		DEFAULT '1900'		NOT NULL,
  `TITLE`		VARCHAR(200)		DEFAULT ''		NOT NULL,
  `CONTENTS`			TEXT						NOT NULL,
  `IMG`					VARCHAR(200)		DEFAULT ''		NOT NULL,
  `THUMB`				VARCHAR(200)		DEFAULT ''		NOT NULL,
  `URL_TITLE`			VARCHAR(200)		DEFAULT ''		NOT NULL,
  `MOVIE_URL`			VARCHAR(200)		DEFAULT ''		NOT NULL,
  `FILENAME`			VARCHAR(200)		DEFAULT ''		NOT NULL,
  `FILENAME_ORG`		VARCHAR(200)		DEFAULT ''		NOT NULL,

  `HIT`			INT(10) UNSIGNED	DEFAULT 0		NOT NULL,
  `STATUS`		ENUM('N','Y')		DEFAULT 'Y'		NOT NULL,
  `FINPUT_DATE`	DATETIME			DEFAULT NOW()			NOT NULL,
  `LINPUT_DATE`	DATETIME			DEFAULT NOW()			NOT NULL,
  
  INDEX `INDEX_PAGE` (`SEQ`,`CODE`,`URL_TITLE`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `PAGE_CONTENTS` (
  `IDX`		INT(10) UNSIGNED					NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FATHER`	INT(10) UNSIGNED		DEFAULT 0		NOT NULL,
  `SEQ`		INT(10) UNSIGNED		DEFAULT 1		NOT NULL,

  `TITLE`	VARCHAR(100)			DEFAULT ''		NOT NULL,
  `FONT`	VARCHAR(20)			DEFAULT ''		NOT NULL,
  `FONT_COLOR`	CHAR(6)				DEFAULT '000000'	NOT NULL,
  `FONT_SIZE`	VARCHAR(6)			DEFAULT ''		NOT NULL,
  `FONT_BOLD`	ENUM('Y','N')			DEFAULT 'N'		NOT NULL,
  `TEXT_LAYOUT`	VARCHAR(20)			DEFAULT ''		NOT NULL,
  `CONTENTS`	TEXT							NOT NULL,
  `IMG`		VARCHAR(200)			DEFAULT ''		NOT NULL,
  `THUMB`	VARCHAR(200)			DEFAULT ''		NOT NULL,
  `HREF`	VARCHAR(200)			DEFAULT ''		NOT NULL,

  `HIT`		INT(10) UNSIGNED		DEFAULT 0		NOT NULL,
  `STATUS`	ENUM('Y','N')			DEFAULT 'Y'		NOT NULL,
  `FINPUT_DATE`	DATETIME						NOT NULL,
  `LINPUT_DATE`	DATETIME						NOT NULL,

  INDEX `INDEX_PAGE_CONTENTS` (`FATHER`,`SEQ`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



CREATE TABLE `TBL_PAGE_STORE` (
  `IDX`		INT(10) UNSIGNED					NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `SEQ`		INT(10) UNSIGNED		DEFAULT 1		NOT NULL,

  `CATEGORY`	ENUM('FLAGSHIP','SHOWROOM')	DEFAULT 'FLAGSHIP'	NOT NULL,
  `TITLE`	VARCHAR(100)			DEFAULT ''		NOT NULL,
  `ADDRESS`	VARCHAR(200)			DEFAULT ''		NOT NULL,
  `TEL`		VARCHAR(20)			DEFAULT ''		NOT NULL,
  `INFO`	VARCHAR(100)			DEFAULT ''		NOT NULL,
  `IMG`		VARCHAR(200)			DEFAULT ''		NOT NULL,
  `THUMB`	VARCHAR(200)			DEFAULT ''		NOT NULL,

  `STATUS`	ENUM('Y','N')			DEFAULT 'Y'		NOT NULL,
  `FINPUT_DATE`	DATETIME						NOT NULL,
  `LINPUT_DATE`	DATETIME						NOT NULL,

  INDEX `INDEX_TBL_PAGE_STORE` (`SEQ`,`CATEGORY`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;





CREATE TABLE `TBL_PAGE_STOCKIST` (
  `IDX`		INT(10) UNSIGNED					NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `SEQ`		INT(10) UNSIGNED		DEFAULT 1		NOT NULL,

  `TITLE`	VARCHAR(100)			DEFAULT ''		NOT NULL,
  `ADDRESS`	VARCHAR(200)			DEFAULT ''		NOT NULL,
  `TEL`		VARCHAR(20)			DEFAULT ''		NOT NULL,
  `LNG`		VARCHAR(50)			DEFAULT ''		NOT NULL,
  `LAT`		VARCHAR(50)			DEFAULT ''		NOT NULL,
  `IMG`		VARCHAR(200)			DEFAULT ''		NOT NULL,
  `THUMB`	VARCHAR(200)			DEFAULT ''		NOT NULL,

  `STATUS`	ENUM('Y','N')			DEFAULT 'Y'		NOT NULL,
  `FINPUT_DATE`	DATETIME						NOT NULL,
  `LINPUT_DATE`	DATETIME						NOT NULL,

  INDEX `INDEX_TBL_PAGE_STOCKIST` (`SEQ`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;




/* 이벤트 */
CREATE TABLE `EVENT` (
  `IDX`			INT(10) UNSIGNED				NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `EVENT_NO`		INT(10) UNSIGNED	DEFAULT 0		NOT NULL,

  `ID`			VARCHAR(200)		DEFAULT ''		NOT NULL,
  `NAME`		VARCHAR(20)		DEFAULT ''		NOT NULL,
  `TEL`			VARCHAR(20)		DEFAULT ''		NOT NULL,
  `EMAIL`		VARCHAR(200)		DEFAULT ''		NOT NULL,
  `ZIPCODE`		VARCHAR(5)			DEFAULT '00000'		NOT NULL,
  `ADDRESS1`	VARCHAR(200)		DEFAULT ''		NOT NULL,
  `ADDRESS2`	VARCHAR(200)		DEFAULT ''		NOT NULL,
  `TXT_1`		VARCHAR(50)		DEFAULT ''		NOT NULL,
  `TXT_2`		VARCHAR(50)		DEFAULT ''		NOT NULL,
  `TXT_3`		VARCHAR(50)		DEFAULT ''		NOT NULL,
  `TXT_4`		VARCHAR(50)		DEFAULT ''		NOT NULL,
  `TXT_5`		VARCHAR(50)		DEFAULT ''		NOT NULL,
  `IP`			VARCHAR(15)		DEFAULT ''		NOT NULL,
  `CONTENTS`		TEXT						NOT NULL,

  `STATUS`		ENUM('N','Y')		DEFAULT 'N'		NOT NULL,
  `FINPUT_DATE`		DATETIME		DEFAULT NOW()		NOT NULL,
  `LINPUT_DATE`		DATETIME		DEFAULT NOW()		NOT NULL,
  
  INDEX `INDEX_EVENT` (`NAME`,`EVENT_NO`,`EMAIL`,`TEL`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `EVENT_INFO` (
  `IDX`			INT(10) UNSIGNED				NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `TITLE`		VARCHAR(100)		DEFAULT ''		NOT NULL,
  `URL`			VARCHAR(200)		DEFAULT ''		NOT NULL,

  `HIT`			INT(10) UNSIGNED	DEFAULT 0		NOT NULL,
  `STATUS`		ENUM('N','Y')		DEFAULT 'Y'		NOT NULL,
  `SDATE`			DATETIME							NULL,
  `EDATE`			DATETIME							NULL,
  `FINPUT_DATE`		DATETIME		DEFAULT NOW()		NOT NULL,
  `LINPUT_DATE`		DATETIME		DEFAULT NOW()		NOT NULL,
  
  INDEX `INDEX_EVENT_INFO` (`TITLE`,`SDATE`,`EDATE`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



CREATE TABLE `EVENT_ENTERCODE` (
  `IDX`				INT(10) UNSIGNED					NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `EVENT_NO`		INT(5) UNSIGNED		DEFAULT 0		NOT NULL,
  `LANGUAGE`		VARCHAR(50)			DEFAULT 'KR'	NOT NULL,
  `CODE`			VARCHAR(12)			DEFAULT ''		NOT NULL,

  `SDATE`			DATETIME							NULL,
  `EDATE`			DATETIME							NULL,
  `CONFIRM_DATE`	DATETIME							NULL,

  `UNLIMIT_YN`		ENUM('N','Y')		DEFAULT 'N'		NOT NULL,
  `USE_YN`			ENUM('N','Y')		DEFAULT 'N'		NOT NULL,
  `STATUS`			ENUM('N','Y')		DEFAULT 'Y'		NOT NULL,

  INDEX `INDEX_EVENT_ENTERCODE` (`EVENT_NO`,`CODE`,`SDATE`,`EDATE`,`USE_YN`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `EVENT_ENTERCODE_LOGIN` (
  `ID`				VARCHAR(50)							NOT NULL PRIMARY KEY,

  `CODE_NO`			INT(5) UNSIGNED		DEFAULT 0		NOT NULL,
  `SESSION_ID`		VARCHAR(50)							NOT NULL,
  `LOGIN_DATE`		DATETIME							NULL,

  `STATUS`			ENUM('N','Y')		DEFAULT 'Y'		NOT NULL,

  INDEX `INDEX_EVENT_ENTERCODE` (`CODE_NO`,`SESSION_ID`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
