<?php
$_TABLE['MEMBER_CAFE24'] = 'MEMBER_CAFE24';

$_TABLE['CONTENTS'] = 'PAGE';
$_TABLE['CONTENTS_DETAIL'] = 'PAGE_CONTENTS';
$_TABLE['STORE'] = 'PAGE_STORE';


/** 이벤트 **/
$_TABLE['EVENT'] = 'EVENT';
$_TABLE['EVENT_INFO'] = 'EVENT_INFO';
$_TABLE['EVENT_CODE'] = 'EVENT_ENTERCODE';
$_TABLE['EVENT_CODE_ENTER'] = 'EVENT_ENTERCODE_LOGIN';

/** 정품코드 **/
$_TABLE['SERIAL'] = 'SERIAL_CODE';
$_TABLE['SERIAL_LOG'] = 'SERIAL_CODE_HISTORY';


/** STOCKIST **/
$_TABLE['STOCKIST'] = 'STOCKIST';
$_TABLE['STOCKIST_STORE'] = 'STOCKIST_STORE';
$_TABLE['STOCKIST_IMAGE'] = 'STOCKIST_IMAGES';


/** 포인트 **/
$_TABLE['POINT'] = 'POINT';
$_TABLE['POINT_USE'] = 'POINT_USEABLE';


/** 카카오 알림톡 **/
$_TABLE['ALIMTALK_TEMPLATE'] = 'KAKAO_ALIMTALK_TEMPLATE';


/** 이전 정보 **/
$_TABLE['OLD_SHOP_GOODS'] = 'BAK_SHOP_GOODS';
$_TABLE['OLD_SHOP_GOODS_OPTION_VAL'] = 'BAK_SHOP_GOODS_OPTION_VALUES';
$_TABLE['OLD_SHOP_GOODS_OPTION'] = 'BAK_SHOP_GOODS_OPTION';



$_TABLE['ENTER'] = 'OFFLINE_ENTERANCE';
?>